minor changes to remove making requirements again

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -34,26 +34,25 @@ jobs:
           echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
           echo "PYTHONPATH=$PYTHONPATH:$(pwd)/test" >> $GITHUB_ENV
         
-      - name: List Repository Files
-        run: ls -R
+      # - name: List Repository Files
+      #   run: ls -R
 
-      - name: Verify requirements.txt Exists
-        run: |
-          if [ ! -f requirements.txt ]; then
-            echo "requirements.txt not found!"
-            exit 1
-          fi
-      
-      - name: Install Python Dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
+      # - name: Verify requirements.txt Exists
+      #   run: |
+      #     if [ ! -f requirements.txt ]; then
+      #       echo "requirements.txt not found!"
+      #       exit 1
+      #     fi
 
   dependencies:
     name: Install Dependencies
     runs-on: ubuntu-latest
     needs: setup
     steps:
+      - name: Install Python Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
@@ -62,8 +61,8 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Install Project Requirements
-        run: make requirements
+      # - name: Install Project Requirements
+      #   run: make requirements
 
   lint-and-test:
     name: Lint and Test
