minor chnages for testing

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -33,16 +33,27 @@ jobs:
         run: |
           echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
           echo "PYTHONPATH=$PYTHONPATH:$(pwd)/test" >> $GITHUB_ENV
+        
+      - name: List Repository Files
+        run: ls -R
+
+      - name: Verify requirements.txt Exists
+        run: |
+          if [ ! -f requirements.txt ]; then
+            echo "requirements.txt not found!"
+            exit 1
+          fi
+      
+      - name: Install Python Dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
 
   dependencies:
     name: Install Dependencies
     runs-on: ubuntu-latest
     needs: setup
     steps:
-      - name: Install Python Dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install -r requirements.txt
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
